### ISSUE TITLE
Is this safe to use now?

### ISSUE THREAD

**Issue by jsnepo** [nexusofdoom/lancache-installer#6] opened 2018-08-27 07:03 UTC

**Comment by tamatoa** [comment] 2018-08-27 07:56
I run this lancache since at least 6 weeks, and it runs like a charm for me. for myself, I have to edit the /etc/resolv.conf and add "nameserver iprouter" to be able to resolve dns. in my dhcp, I put as primary dns my lancache ip.

**Comment by jsnepo** [comment] 2018-08-27 09:13
I mean the installer. Does it work? I have tried it but it's not working or maybe I am missing something.

**Comment by nexusofdoom** [comment] 2018-08-27 12:58
re-working it at the this time it should be live by the end of the month.

**Comment by BumpyClock** [comment] 2018-08-27 16:17
I used it earlier this weekend and it worked for me, as you're working on a new version would it be possible to scan for open IPs on the network or ask for an ip range to assign it to various proxies?

That was the cause of my issues, it assigned a few IPs that were already on the network and a few cache's were working and rest didn't. 

Thank you for putting in the work to creating this.

**Comment by jsnepo** [comment] 2018-08-28 10:58
Great. Will wait for your update.

**Comment by jsnepo** [comment] 2018-09-01 06:44
Got this working.  I'm wondering how do you run netdata? I installed it but it doesn't seem like it installed properly.  I checked if the service is running and it couldn't find it.

**Comment by nexusofdoom** [comment] 2018-09-01 12:56
If installed it would be like this.
http://192.168.0.2:19999/#menu_system_submenu_cpu;theme=slate

Note IP is the main interface IP of your setup.

**Comment by nexusofdoom** [comment] 2018-09-01 13:44
looks like 18.04.1 you can install netdata with apt-get 

https://www.howtoforge.com/tutorial/how-to-install-netdata-monitoring-tool-on-ubuntu/

I will update this soon.
thanks

**Comment by jsnepo** [comment] 2018-09-01 15:07
Yup. That's what I did.  I have another question.  How do you clear the cache?

**Comment by nexusofdoom** [comment] 2018-09-01 15:11
the date is located in /srv/lancache/data/ "servicename" steam blizzard origin 
all you need to do is delete the files and folder inside that folder leaving the folder.

example 
/srv/lancache/data/steam "keep"

delete 
/srv/lancache/data/steam/"otherfolder names" delete.

**Closed** 2018-09-01 15:34 UTC

**Comment by nexusofdoom** [comment] 2018-09-01 15:38
Your Welcome. 
Thank you for using Lancache
